name: topic_to_feature_store
language: python
variables:
  - name: KAFKA_INPUT_TOPIC
    inputType: InputTopic
    description: ''
    defaultValue: ohlcv
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: ''
    defaultValue: consumer_group_ohlcv_to_feature_store
    required: true
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    description: ''
    defaultValue: ohlcv_feature_group
    required: true
  - name: FEATURE_GROUP_VERSION
    inputType: FreeText
    description: ''
    defaultValue: 1
    required: false
  - name: FEATURE_GROUP_PRIMARY_KEYS
    inputType: FreeText
    description: ''
    defaultValue: '["product_id", "timestamp_ms"]'
    required: true
  - name: FEATURE_GROUP_EVENT_TIME
    inputType: FreeText
    description: ''
    defaultValue: timestamp_ms
    required: true
  - name: START_OFFLINE_MATERIALIZATION
    inputType: FreeText
    description: ''
    defaultValue: false
    required: true
  - name: HOPSWORKS_PROJECT_NAME
    inputType: Secret
    description: ''
    defaultValue: HOPSWORKS_PROJECT_NAME
    required: true
  - name: HOPSWORKS_API_KEY
    inputType: Secret
    description: ''
    defaultValue: HOPSWORKS_API_KEY
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
