name: topic_to_feature_store
language: python
variables:
  - name: KAFKA_INPUT_TOPIC
    inputType: InputTopic
    description: ''
    defaultValue: ohlcv
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: ''
    defaultValue: consumer_group_ohlcv_to_feature_store
    required: true
  - name: FEATURE_GROUP_NAME
    inputType: FreeText
    description: ''
    defaultValue: ohlcv_feature_group
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
