name: trade_producer
language: python
variables:
  - name: KAFKA_TOPIC
    inputType: OutputTopic
    description: ''
    defaultValue: trade
    required: true
  - name: PRODUCT_IDS
    inputType: FreeText
    description: List of currencies to get trades for
    defaultValue: '["BTC/USD", "ETH/USD"]'
    required: true
  - name: LIVE_OR_HISTORICAL
    inputType: FreeText
    description: ''
    defaultValue: live
    required: true
  - name: LAST_N_DAYS
    inputType: FreeText
    description: ''
    defaultValue: 90
    required: false
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
