name: price_predictor
language: python
variables:
  - name: FEATURE_VIEW_NAME
    inputType: FreeText
    description: ''
    defaultValue: ohlcv_feature_view
    required: true
  - name: FEATURE_VIEW_VERSION
    inputType: FreeText
    description: ''
    defaultValue: 1
    required: true
dockerfile: Dockerfile
runEntryPoint: src/training.py
defaultFile: src/training.py
