version: '3.7'
name: feature-pipeline
networks:
  redpanda_network:
    external: true
services:

  trade_producer:
    build:
      context: ../services/trade_producer
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/trade_producer/live.prod.env

  trade_to_ohlcv:
    build:
      context: ../services/trade_to_ohlcv
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/trade_to_ohlcv/live.prod.env

  topic_to_feature_store:
    build:
      context: ../services/topic_to_feature_store
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/topic_to_feature_store/live.prod.env
      - ../services/topic_to_feature_store/credentials.env